### ISSUE TITLE
Toml files for mozilla/bedrock are rejected by 9.0.0

### ISSUE THREAD

**Issue by stevejalim** [mozilla/compare-locales#12]
Over on https://github.com/mozilla/bedrock/, I had to upgrade compare-locales to 9.0.0 to ensure requirements compatibility with the latest versions of fluent-runtime and fluent-syntax. (PR [here](https://github.com/mozilla/bedrock/pull/12890))

However, while our main tests pass, some of our linting using compare-locales [fails](https://github.com/mozilla/bedrock/actions/runs/4469601140/jobs/7853799415) under 9.0.0

I'm thinking it's possibly related to the switch from `pytoml` to `toml`, though I am still exploring/

### To reproduce 

1. Check out https://github.com/stevejalim/bedrock/tree/2023-03-20--dependency-bumps (my fork of Bedrock), 
2. Make and activate a venv
3. Run `make install-local-python-deps` to get all the latest dependencies installed.
4. Then try the linter against a toml file - it will fail:

```
~/Code/bedrock $ moz-l10n-lint l10n/l10n-pontoon.toml
Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/bedrock39/bin/moz-l10n-lint", line 8, in <module>
    sys.exit(main())
  File "/Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages/compare_locales/lint/cli.py", line 61, in main
    pc = paths.TOMLParser().parse(args.l10n_toml, env={'l10n_base': l10n_base})
  File "/Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages/compare_locales/paths/configparser.py", line 35, in parse
    self.load(ctx)
  File "/Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages/compare_locales/paths/configparser.py", line 55, in load
    ctx.data = toml.load(fin)
  File "/Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages/toml/decoder.py", line 187, in loads
    raise TypeError("Expecting something like a string")
TypeError: Expecting something like a string
```

5. Downgrade to 8.2.1 and that works fine. 
```
(bedrock39) [steve] ~/Code/bedrock $ pip install -U compare-locales==8.2.1
Collecting compare-locales==8.2.1
  Using cached compare_locales-8.2.1-py2.py3-none-any.whl (128 kB)
Requirement already satisfied: six in /Users/steve/.pyenv/versions/3.9.10/envs/bedrock39/lib/python3.9/site-packages (from compare-locales==8.2.1) (1.16.0)
Collecting fluent.syntax<0.19,>=0.18.0
  Using cached fluent.syntax-0.18.1-py2.py3-none-any.whl (16 kB)
Collecting pytoml
  Using cached pytoml-0.1.21-py2.py3-none-any.whl (8.5 kB)
Installing collected packages: pytoml, fluent.syntax, compare-locales
  Attempting uninstall: fluent.syntax
    Found existing installation: fluent.syntax 0.19.0
    Uninstalling fluent.syntax-0.19.0:
      Successfully uninstalled fluent.syntax-0.19.0
  Attempting uninstall: compare-locales
    Found existing installation: compare-locales 9.0.0
    Uninstalling compare-locales-9.0.0:
      Successfully uninstalled compare-locales-9.0.0
Successfully installed compare-locales-8.2.1 fluent.syntax-0.18.1 pytoml-0.1.21
(bedrock39) [steve] ~/Code/bedrock $ moz-l10n-lint l10n/l10n-pontoon.toml
(bedrock39) [steve] 
```

(Unfortunately our dependency manager `pip-compile` won't resolve a version of dependencies using 8.2.1 and the latest fluent-* packages). Any suggestions on what might fix this? We can reformat our toml files, but the error above looks more lik we're expecting a string but getting a bytestring and therefore choking. With the debugger I see:

```185  	    if not isinstance(s, basestring):
186  ->	        raise TypeError("Expecting something like a string")
```

where `s` is

```
b'# Entrypoint for community localization.\n# Edits to add content for l10n should be made in configs/pontoon.toml\n\nbasepath = "."\n\n[[includes]]\n    path = "configs/pontoon.toml"\n\n[[excludes]]\n    path = "configs/vendor.toml"\n\n[[excludes]]\n    path = "configs/special-templates.toml"\n'
```

and `isinstance(s, basestring)` therefore returns `False`

**Comment by flodolo** [comment]
This is broken in at least the two places I've checked so far (l10n linter, extraction script used in Transvision).

They all choke on `paths.TOMLParser().parse(self.toml_path, env={"l10n_base": ""})`

**Comment by flodolo** [comment]
`toml.load()` is clearly not a 1:1 replacement of `pytoml.load()`.

From a quick test, this seems to die because we [open the config file](https://github.com/mozilla/compare-locales/blob/main/compare_locales/paths/configparser.py#L54) with `rb`?
https://github.com/uiri/toml/blob/3f637dba5f68db63d4b30967fedda51c82459471/toml/decoder.py#L185

And tests for paths only load the toml config with `toml.loads()` 😞
